apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  namespace: default
  labels:
    app: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlantis
  template:
    metadata:
      labels:
        app: atlantis
    spec:
      containers:
      - name: atlantis
        image: runatlantis/atlantis:latest
        env:
        - name: ATLANTIS_PORT
          value: "4141"
        - name: ATLANTIS_GH_USER
          value: your-cicd-user
        - name: ATLANTIS_LOG_LEVEL
          value: debug
        - name: ATLANTIS_GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: token
        - name: ATLANTIS_GH_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: webhook-secret
        - name: ATLANTIS_REPO_WHITELIST
          value: github.com/yourorg/terraform-*
        ports:
        - name: atlantis
          containerPort: 4141
        resources:
          requests:
            memory: 300Mi
            cpu: 1000m
          limits:
            memory: 300Mi
            cpu: 1000m
        readinessProbe:
          httpGet:
            path: /
            port: 4141
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 4141
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
  selector:
    app: atlantis

