apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
  namespace: default
spec:
  serviceName: atlantis
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0 # Automatic update
  selector:
    matchLabels:
      app: atlantis
  template:
    metadata:
      labels:
        app: atlantis
    spec:
      securityContext:
        fsGroup: 1000 # atlantis group (1000) read/write access to volumes
      containers:
      - name: atlantis
        image: runatlantis/atlantis:v0.3.5
        env:
        - name: ATLANTIS_PORT
          value: "4141"
        - name: ATLANTIS_DATA_DIR
          value: /atlantis
        - name: ATLANTIS_GH_USER
          value: your-cicd-user
        - name: ATLANTIS_GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: token
        - name: ATLANTIS_GH_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: webhook-secret
        - name: ATLANTIS_REPO_WHITELIST
          value: github.com/yourorg/terraform-*
        volumeMounts:
        - name: atlantis-storage
          mountPath: /atlantis
        ports:
        - name: atlantis
          containerPort: 4141
        resources:
          requests:
            memory: 300Mi
            cpu: 1000m
          limits:
            memory: 300Mi
            cpu: 1000m
        readinessProbe:
          httpGet:
            path: /
            port: 4141
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 4141
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
  volumeClaimTemplates:
  - metadata:
      name: atlantis-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
  selector:
    app: atlantis

