apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.name" . }}-webhook
  labels:
    app: {{ template "atlantis.name" . }}
    chart: {{ template "atlantis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  token: {{ print .Values.webhook.token | b64enc }}
  webhook-secret: {{ print .Values.webhook.secret | b64enc }}