name: atlantis-image

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build atlantis:latest image
      run: |
        make build-service
        docker build -t ghcr.io/runatlantis/atlantis:latest .
    - name: publish atlantis:latest image
      run: |
        docker push ghcr.io/runatlantis/atlantis:latest
