name: atlantis-image

on:
  push:
    branches:
      - "master"
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Publish latest image to container registry
    - name: build atlantis:latest image
      if: ${{ github.event_name == 'push'}}
      run: |
        make build-service
        docker build -t ghcr.io/runatlantis/atlantis:latest .
    - name: publish atlantis:latest image
      if: ${{ github.event_name == 'push'}}
      run: |
        docker push ghcr.io/runatlantis/atlantis:latest

    # Publish release to container registry
    - name: build atlantis release image
      if: ${{ github.event_name == 'release'}}
      run: |
        make build-service
        docker build -t ghcr.io/runatlantis/atlantis:$GITHUB_REF .
    - name: publish atlantis release image
      if: ${{ github.event_name == 'release'}}
      run: |
        docker push ghcr.io/runatlantis/atlantis:$GITHUB_REF
